# Segredos para autenticação de usuário da Web
[google_oauth]
client_id = "1070777164287-j28taj7egojeirc4evet3ata98ashvoe.apps.googleusercontent.com"
client_secret = "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"
redirect_uri = "http://localhost:8501"
project_id = "monitoramento-lancamentos-rco"

# Mapeamento de e-mails de usuários para seus respectivos datasets
[office_mapping]
"s.alvaro@escola.pr.gov.br" = "Lancamentos_lrco_alvaro_Teste"
"nretoo_crte@escola.pr.gov.br" = "Lancamentos_lrco_toledo"
"nretoo_bancodedados@escola.pr.gov.br" = "Lancamentos_lrco_toledo"